### ISSUE TITLE
ประชุมครั้งที่ 14 01/03/2567

### ISSUE THREAD

**Issue by AmericanoHoney** [Akkarapo/I-am-STAY#21]

**Comment by AmericanoHoney** [comment]
ความคืบหน้า 01/03/2024
มพ
-กำลังพยายามทำประวัติ+ส่งเลขโต๊ะมาใส่ในตั๋ว
-รวมไฟล์กับเต้ยอยู่
ก้อง 
- แก้บัคให้เนปจูน + ทำให้ทุกระบบเป็นไฟล์ io แก้หน้าตาเมลตอนลืมรหัสให้ดูดีแล้ว เหลือแค่เก็บงาน
เนป 
- ก้องเพิ่งแก้บัคให้ กำลังจะเริ่มทำระบบแอดมินเตะโต๊ะ (ระบบอ่านไฟล์แล้วขึ้นว่ามีโต๊ะไหนถูกจองแล้วบ้าง เสร็จแล้ว) 
คิดไว้ว่าแอดมินก็จองโต๊ะอะไรได้แบบ userอื่น เพราะชีวิตจริงมันก็มีคนโทรจองโต๊ะอยู่แล้ว  จะได้ไม่แก้โค้ดเยอะด้วย  
เต้ย
-เปลี่ยนUIแล้ว เหลือนับจำนวนโต๊ะ 
-visualค้าง เปิดใหม่ละพัง

**Comment by AmericanoHoney** [comment]
https://github.com/Akkarapo/I-am-STAY/assets/141731125/e48f023c-7621-4526-af41-c3c37135febf

คลิปจากใจเด็กน้อยขอบตาดำๆ

**Comment by Akkarapo** [comment]
แพ็กเกจ ป่วย ไปไม่รอดดดดดดด
